// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Other.proto

package com.mogujie.tt.protobuf;

public final class IMOther {
  private IMOther() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMHeartBeat)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code IM.Other.IMHeartBeat}
   *
   * <pre>
   *cmd id:  		0x0701
   * </pre>
   */
  public static final class IMHeartBeat extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMHeartBeat)
      IMHeartBeatOrBuilder {
    // Use IMHeartBeat.newBuilder() to construct.
    private IMHeartBeat(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMHeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMHeartBeat defaultInstance;
    public static IMHeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public IMHeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMHeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<IMHeartBeat>() {
      public IMHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMHeartBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMHeartBeat> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMHeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Other.IMHeartBeat}
     *
     * <pre>
     *cmd id:  		0x0701
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMHeartBeat, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMHeartBeat)
        com.mogujie.tt.protobuf.IMOther.IMHeartBeatOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.mogujie.tt.protobuf.IMOther.IMHeartBeat getDefaultInstanceForType() {
        return com.mogujie.tt.protobuf.IMOther.IMHeartBeat.getDefaultInstance();
      }

      public com.mogujie.tt.protobuf.IMOther.IMHeartBeat build() {
        com.mogujie.tt.protobuf.IMOther.IMHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.tt.protobuf.IMOther.IMHeartBeat buildPartial() {
        com.mogujie.tt.protobuf.IMOther.IMHeartBeat result = new com.mogujie.tt.protobuf.IMOther.IMHeartBeat(this);
        return result;
      }

      public Builder mergeFrom(com.mogujie.tt.protobuf.IMOther.IMHeartBeat other) {
        if (other == com.mogujie.tt.protobuf.IMOther.IMHeartBeat.getDefaultInstance()) return this;
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.tt.protobuf.IMOther.IMHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.tt.protobuf.IMOther.IMHeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Other.IMHeartBeat)
    }

    static {
      defaultInstance = new IMHeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Other.IMHeartBeat)
  }

  public interface IMCarInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMCarInfoReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 user_id = 1;</code>
     *
     * <pre>
     *消息发送id
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint64 user_id = 1;</code>
     *
     * <pre>
     *消息发送id
     * </pre>
     */
    long getUserId();

    /**
     * <code>optional bytes user_info = 2;</code>
     *
     * <pre>
     *用户信息数据
     * </pre>
     */
    boolean hasUserInfo();
    /**
     * <code>optional bytes user_info = 2;</code>
     *
     * <pre>
     *用户信息数据
     * </pre>
     */
    com.google.protobuf.ByteString getUserInfo();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Other.IMCarInfoReq}
   */
  public static final class IMCarInfoReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMCarInfoReq)
      IMCarInfoReqOrBuilder {
    // Use IMCarInfoReq.newBuilder() to construct.
    private IMCarInfoReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMCarInfoReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMCarInfoReq defaultInstance;
    public static IMCarInfoReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMCarInfoReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMCarInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userInfo_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000004;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMCarInfoReq> PARSER =
        new com.google.protobuf.AbstractParser<IMCarInfoReq>() {
      public IMCarInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMCarInfoReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMCarInfoReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required uint64 user_id = 1;</code>
     *
     * <pre>
     *消息发送id
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 user_id = 1;</code>
     *
     * <pre>
     *消息发送id
     * </pre>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USER_INFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString userInfo_;
    /**
     * <code>optional bytes user_info = 2;</code>
     *
     * <pre>
     *用户信息数据
     * </pre>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes user_info = 2;</code>
     *
     * <pre>
     *用户信息数据
     * </pre>
     */
    public com.google.protobuf.ByteString getUserInfo() {
      return userInfo_;
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      userId_ = 0L;
      userInfo_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, userInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, userInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMCarInfoReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Other.IMCarInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMCarInfoReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMCarInfoReq)
        com.mogujie.tt.protobuf.IMOther.IMCarInfoReqOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMCarInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        userInfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoReq getDefaultInstanceForType() {
        return com.mogujie.tt.protobuf.IMOther.IMCarInfoReq.getDefaultInstance();
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoReq build() {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoReq buildPartial() {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoReq result = new com.mogujie.tt.protobuf.IMOther.IMCarInfoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userInfo_ = userInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.mogujie.tt.protobuf.IMOther.IMCarInfoReq other) {
        if (other == com.mogujie.tt.protobuf.IMOther.IMCarInfoReq.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserInfo()) {
          setUserInfo(other.getUserInfo());
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.tt.protobuf.IMOther.IMCarInfoReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>required uint64 user_id = 1;</code>
       *
       * <pre>
       *消息发送id
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 user_id = 1;</code>
       *
       * <pre>
       *消息发送id
       * </pre>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required uint64 user_id = 1;</code>
       *
       * <pre>
       *消息发送id
       * </pre>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        
        return this;
      }
      /**
       * <code>required uint64 user_id = 1;</code>
       *
       * <pre>
       *消息发送id
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        
        return this;
      }

      private com.google.protobuf.ByteString userInfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes user_info = 2;</code>
       *
       * <pre>
       *用户信息数据
       * </pre>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes user_info = 2;</code>
       *
       * <pre>
       *用户信息数据
       * </pre>
       */
      public com.google.protobuf.ByteString getUserInfo() {
        return userInfo_;
      }
      /**
       * <code>optional bytes user_info = 2;</code>
       *
       * <pre>
       *用户信息数据
       * </pre>
       */
      public Builder setUserInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userInfo_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes user_info = 2;</code>
       *
       * <pre>
       *用户信息数据
       * </pre>
       */
      public Builder clearUserInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userInfo_ = getDefaultInstance().getUserInfo();
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Other.IMCarInfoReq)
    }

    static {
      defaultInstance = new IMCarInfoReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Other.IMCarInfoReq)
  }

  public interface IMCarInfoRepOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Other.IMCarInfoRep)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode();

    /**
     * <code>required uint64 user_id = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    long getUserId();

    /**
     * <code>optional bytes return_info = 3;</code>
     */
    boolean hasReturnInfo();
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    com.google.protobuf.ByteString getReturnInfo();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Other.IMCarInfoRep}
   */
  public static final class IMCarInfoRep extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Other.IMCarInfoRep)
      IMCarInfoRepOrBuilder {
    // Use IMCarInfoRep.newBuilder() to construct.
    private IMCarInfoRep(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMCarInfoRep(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMCarInfoRep defaultInstance;
    public static IMCarInfoRep getDefaultInstance() {
      return defaultInstance;
    }

    public IMCarInfoRep getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMCarInfoRep(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mogujie.tt.protobuf.IMBaseDefine.ResultType value = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              returnInfo_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000008;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMCarInfoRep> PARSER =
        new com.google.protobuf.AbstractParser<IMCarInfoRep>() {
      public IMCarInfoRep parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMCarInfoRep(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMCarInfoRep> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private com.mogujie.tt.protobuf.IMBaseDefine.ResultType resultCode_;
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
     */
    public com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode() {
      return resultCode_;
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 user_id = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int RETURN_INFO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString returnInfo_;
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    public boolean hasReturnInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes return_info = 3;</code>
     */
    public com.google.protobuf.ByteString getReturnInfo() {
      return returnInfo_;
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      resultCode_ = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      userId_ = 0L;
      returnInfo_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, returnInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, returnInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMOther.IMCarInfoRep prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Other.IMCarInfoRep}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMOther.IMCarInfoRep, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Other.IMCarInfoRep)
        com.mogujie.tt.protobuf.IMOther.IMCarInfoRepOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMOther.IMCarInfoRep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        returnInfo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoRep getDefaultInstanceForType() {
        return com.mogujie.tt.protobuf.IMOther.IMCarInfoRep.getDefaultInstance();
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoRep build() {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoRep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.tt.protobuf.IMOther.IMCarInfoRep buildPartial() {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoRep result = new com.mogujie.tt.protobuf.IMOther.IMCarInfoRep(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.returnInfo_ = returnInfo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.mogujie.tt.protobuf.IMOther.IMCarInfoRep other) {
        if (other == com.mogujie.tt.protobuf.IMOther.IMCarInfoRep.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasReturnInfo()) {
          setReturnInfo(other.getReturnInfo());
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.tt.protobuf.IMOther.IMCarInfoRep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.tt.protobuf.IMOther.IMCarInfoRep) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.mogujie.tt.protobuf.IMBaseDefine.ResultType resultCode_ = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public com.mogujie.tt.protobuf.IMBaseDefine.ResultType getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public Builder setResultCode(com.mogujie.tt.protobuf.IMBaseDefine.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = com.mogujie.tt.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        
        return this;
      }

      private long userId_ ;
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        
        return this;
      }
      /**
       * <code>required uint64 user_id = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        
        return this;
      }

      private com.google.protobuf.ByteString returnInfo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public boolean hasReturnInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public com.google.protobuf.ByteString getReturnInfo() {
        return returnInfo_;
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public Builder setReturnInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        returnInfo_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes return_info = 3;</code>
       */
      public Builder clearReturnInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        returnInfo_ = getDefaultInstance().getReturnInfo();
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Other.IMCarInfoRep)
    }

    static {
      defaultInstance = new IMCarInfoRep(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Other.IMCarInfoRep)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
